### ISSUE TITLE
Release Version v2.2.0 to npm registry

### ISSUE THREAD

**Issue by ghost** [asciidoctor/gulp-asciidoctor#19]
To publish the new version 2.2.0 to npm, the following has to be done:

1. Check npm outdated and push outdated modules to latest version
2. Create a new Github release with version v2.2.0
3. Publish the release with npm publish
4. Delete the pull request branches

**Comment by ghost** [comment]
Which user account should be used to log into npm?

I have my own, so I could use it

**Comment by ghost** [comment]
Nice! This can be done with a GitHub action. See

https://sergiodxa.com/articles/github-actions-npm-publish/

**Comment by ggrossetie** [comment]
Yes! The latest release of asciidoctor.js was published using GitHub Actions. But it's not the most straightforward because we have multiple packages.
You can have a look at: https://github.com/Mogztter/asciidoctor-kroki/blob/master/.github/workflows/release.yml

Ping @mojavelinux  for the `@asciidoctor` org on npmjs. I guess the right way to do it is to create a bot account (the associated npm token will be configured as a secret in this project) then every contributors can do a release (if they can push a tag on origin).

**Comment by ghost** [comment]
Hello @mojavelinux, 
gulp-asciidoctor is ready to be published on npmjs.com.

To do that, I would suggest the following:
- @mojavelinux creates a bot account on npmjs.com
- @mojavelinux creates an access token for publishing gulp-asciidoctor on npmjs.com
- @mojavelinux sets up the access token on https://github.com/asciidoctor/gulp-asciidoctor/settings/secrets
- @henriette-einstein implements a Github action that automatically publishes the release to npmjs.com, once a relaese is created in Github
- @Mogztter reviews the alction
- @henriette-einstein creates a Asciidoctor document that describes the mechanism for publishing gulp-asciidoctor

Is that ok for both of you?

I could also structure the documentation for Antora usage if you think that this is useful. I haven't done that yet, but I'm sure it is not too complicated.

**Comment by ghost** [comment]
I don't know if that is the correct way to do it, but I assigned this issue to @mojavelinux 

I don't want to offend anybody if this is not welcome.

**Comment by ghost** [comment]
This issue is outdated. Now using the credentials of @Mogztter
